### ISSUE TITLE
multilayer search and appearance table

### ISSUE THREAD

**Issue by vzlprojects** [andreaordonselli/qgis2o.gis#14]
Good morning! 
A few days ago I suggested some updates, but then I saw that they are in the most complete version (thanks for the coffee).
However, I can't get the option to search in one or more layers to appear (apparence Tab).
Am I doing something wrong? 
By the way, how can I remove the tab sidebar?
edit: maybe in the appearance table we will have the possibility to choose what we want to appear on the map. Just a tip.

Thanks again for your excellent work!

plugin version: 2.22.0
QGIS: 3.38

![1](https://github.com/user-attachments/assets/1f7e876e-e6ba-4f41-878c-0b3c26866a88)

**Comment by andreaordonselli** [comment]
Good morning,
the features you request are expected in future versions of the software. You will be notified with a newsletter of the new version and if you have active recurring donation you will receive it.

For the moment you will have to manually set up the quick search as explained in this chapter of the documentation https://www.opengis.it/docs/o-gis/opengis-configure-the-map/#9-toc-title

To disable the sidebar is simple but at the moment all the other buttons will have to be manually moved to the left to align them with the left side of the monitor (In the future I will make it automatic).
After producing O.GIS, open the folder and edit the index.html file, adding this code before closing the `</head>` section

```css
<style>
     #sidebar {
          display: none;
     }

     #form_logo {
          left: 8px;
     }

     etc....
     etc.... for other element
</style>
</head>   <--- closure of the head section (Don't repeat this code, it already exists)
```
