### ISSUE TITLE
Enhancement Request for Mobile View Functionality in o.gis Plugin [SOLVED]

### ISSUE THREAD

**Issue by andreaordonselli** [andreaordonselli/qgis2o.gis#15]
Dear Andrea Ordonselli,

I hope this email finds you well. First and foremost, I want to express my appreciation for the o.gis plugin. It has been an incredible tool for my GIS-based HTML project, and I am very impressed with its capabilities. I would like to extend my best wishes for your continued success with this plugin.

I have been using the o.gis plugin on the desktop version without any issues, and it functions perfectly. However, I have noticed that several options are disabled or hidden when switching to mobile or touch devices. For my project, it is crucial to have the following features available on mobile devices as well:

1. Transparency Layer: I would like the transparency layer option to be enabled on mobile devices, as it is an essential feature for my project.

2. Permalink Functionality: The ability to copy the exact location of the map using the permalink option is vital. It would be great if this could be enabled on mobile devices as well.

3. Measure and Draw Icons: The measure and draw icons are crucial tools for my project. Could these be enabled for mobile devices as well?

4. (My Suggestion) Image Save/Download with Watermark: It would be helpful if the image save or download option could be added when someone clicks the print button. Additionally, having a logo or watermark on the saved image, corresponding to the device screen size or viewport, would be an excellent enhancement.

I believe enabling these features for mobile devices would significantly enhance the usability of the o.gis plugin for users like me who often work on touch devices.

Thank you for your attention to this matter, and I look forward to any updates or advice you may have on this. Once again, I appreciate your efforts in developing such a fantastic tool.

Best regards,
W.

**Comment by andreaordonselli** [comment]
Hi W. ,
to reactivate the requested functionality, simply act on the CSS code that hides them.
Follow the documentation in this chapter [One-off or permanent setups](https://www.opengis.it/docs/o-gis/o-gis-configure-the-map/#1-toc-title) to edit a single exported project or all the ones you export.

Specifically, you can edit the html file before closing the `</head>` by adding this css code:
1. Transparency Layer
```css
<style>
	.ol-touch .layerswitcher-opacity {
		display: block;
		right: 12px;
	}
	.ol-touch .layerswitcher-opacity-label {
		display: block;
		right: 37px;
	}
	.ol-touch .panel-container {
		width: 303px!important;
	}
</style>
```

2. Permalink Functionality
```css
<style>
	.ol-touch .ol-permalink {
		display: block;
		right: 73px;
		top: 49px;
	}
</style>
```

3. Measure and Draw
```css
<style>	
	.ol-touch .measure-control {
		display: block;
		top: 158px !important;
		left: 0px !important;
	}		
	.ol-touch .ol-bar {
		display: block;
		left: 8px;
		top: 171px;
	}
</style>
```
4. Adding the possibility of printing a logo is an excellent idea, I'll mark it among the things to implement. I would exclude the Watermark. 
At the moment, since printing is started through the same browser, it is only possible to save the PDF. Adding the possibility of downloading the image would mean adding a further library and the project already integrates many. Do you think it's essential? After all, having a PDF you can convert it into an image with any tool, even the web.
