### ISSUE TITLE
Popup too narrow for audio bar

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#36]
Hello,
I use audio files. 
Command in QGIS: 
<audio width=“100%”src=“images/testaudio_1.mp3” controls autoplay>
However, it is cut off in the smartphone portrait view.

![Image](https://github.com/user-attachments/assets/ffdb75e6-dda8-41da-a8e2-ae191aa20c3b)

Best regards

**Comment by jukos** [comment]
http://perezoso.de/qgis/testmap.zip

name:   qgis
password:   qgis2o.gis

I delete the file after downloading.

**Comment by andreaordonselli** [comment]
Test if this works fine:
<audio style="width:110px;" src="images/testaudio_1.mp3" controls="" autoplay="" ></audio>

![Image](https://github.com/user-attachments/assets/50a997f7-22f5-44e6-8495-d8ad4e6b9c7d)

**Comment by jukos** [comment]
![Image](https://github.com/user-attachments/assets/4a0676f2-6c60-4183-af00-2df76c719493)
Thanks for the effort. Does not work so well.
I have now found an (indirect) solution.
I have inserted another picture. The image is a white line, 300px wide and 1px high. This does not make the popup smaller and the audio bar is displayed correctly.

**Comment by jukos** [comment]
Is it possible to set the popup width only for mobile / smartphones?
Greetings

**Comment by andreaordonselli** [comment]
Yes, in the file `o.gis_style.css`, this instruction is present:
```css
		@media screen and (max-width: 649px) {
			.ol-popup .ol-popupfeature table td {
			max-width: 110px;
			word-wrap: break-word;
			min-width: 80px;
			}					
		}
```

You can overwrite it before the closing of your `</head>` in the `index.html` file (or in the `template`) by modifying `td` `max-width` like in this example
```css
		@media screen and (max-width: 649px) {
			.ol-popup .ol-popupfeature table td {
			max-width: 300px;
			word-wrap: break-word;
			min-width: 80px;
			}					
		}
```

Let me know if it’s a solution that solves your problem.
